name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  Scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Build
        run: npm install
      - name: Run Your Action
        run: npm test
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Saving updated codes
